<?php

namespace App\Services\AI\Providers;

use Illuminate\Support\Str;

class MockProvider implements AIProviderInterface
{
    protected string $name = 'Mock Provider';
    protected bool $enabled = true;

    public function generateText(string $prompt, array $context = []): array
    {
        // Simulate processing delay
        usleep(100000); // 100ms

        $projectName = $context['project']['name'] ?? 'Untitled Project';
        $sessionName = $context['session']['name'] ?? 'Untitled Session';

        // Generate context-aware mock text
        $textSamples = [
            "Here is a creative continuation for \"{$sessionName}\" in the project \"{$projectName}\":\n\n" . 
            "The early morning light cast long shadows across the ancient courtyard. " .
            "Characters gathered in whispered讨论, their fates intertwined by forces beyond their understanding. " .
            "As the sun rose, a new chapter began—one that would echo through the ages.\n\n" .
            "This is sample text generated by the mock AI provider. In production, this would be replaced with actual AI-generated content.",

            "Creative writing for \"{$sessionName}\":\n\n" .
            "In the heart of the bustling city, a hidden alley led to an ancient library. " .
            "Dust motes danced in beams of light that pierced the darkened shelves. " .
            "The librarian, an elderly woman with knowing eyes, looked up as the door creaked open.\n\n" .
            "[Sample content for development]",

            "Story continuation:\n\n" .
            "The protagonist stood at the crossroads, multiple paths stretching into the unknown. " .
            "Each choice promised adventure, danger, and the possibility of transformation. " .
            "With a deep breath, they stepped forward into destiny.\n\n" .
            "[Mock output for local development]",
        ];

        return [
            'success' => true,
            'content' => $textSamples[array_rand($textSamples)],
            'model' => 'mock-text-v1',
            'tokens' => Str::random(20),
            'metadata' => [
                'provider' => $this->name,
                'prompt_length' => strlen($prompt),
                'context_keys' => array_keys($context),
                'project' => $projectName,
                'generated_at' => now()->toISOString(),
            ],
        ];
    }

    public function generateImage(string $prompt, array $references = []): array
    {
        // Simulate processing delay
        usleep(200000); // 200ms

        // Generate unique seed for this image
        $seed = Str::random(8);
        
        // Use placeholder service with prompt-encoded text
        $encodedPrompt = urlencode(substr($prompt, 0, 30));
        
        // Multiple image URLs at different sizes
        $images = [
            [
                'url' => "https://picsum.photos/seed/{$seed}/512/512",
                'thumbnail_url' => "https://picsum.photos/seed/{$seed}/256/256",
                'width' => 512,
                'height' => 512,
                'seed' => $seed,
                'prompt' => $prompt,
            ]
        ];

        // Generate multiple variations if requested
        if (isset($context['variations']) && $context['variations'] > 1) {
            for ($i = 1; $i < $context['variations']; $i++) {
                $images[] = [
                    'url' => "https://picsum.photos/seed/" . Str::random(8) . "/512/512",
                    'thumbnail_url' => "https://picsum.photos/seed/" . Str::random(8) . "/256/256",
                    'width' => 512,
                    'height' => 512,
                    'seed' => Str::random(8),
                    'prompt' => $prompt,
                ];
            }
        }

        return [
            'success' => true,
            'images' => $images,
            'model' => 'mock-image-v1',
            'metadata' => [
                'provider' => $this->name,
                'prompt_length' => strlen($prompt),
                'reference_count' => count($references),
                'generated_at' => now()->toISOString(),
                'placeholder' => 'Using picsum.photos for development',
            ],
        ];
    }

    public function generateStoryboard(string $prompt, array $context = []): array
    {
        // Simulate processing delay
        usleep(300000); // 300ms

        $frameCount = $context['frame_count'] ?? 4;
        $frames = [];

        $descriptions = [
            'Wide shot of the setting sun casting golden light across the landscape',
            'Medium shot of main character contemplating their next move',
            'Close-up detail shot highlighting important story element',
            'Action shot capturing a pivotal moment',
            'Atmospheric establishing shot showing the mood',
            'Two-shot of characters in conversation',
            'POV shot from character perspective',
            'Dramatic low-angle shot emphasizing power',
        ];

        for ($i = 0; $i < $frameCount; $i++) {
            $seed = Str::random(8);
            $description = $descriptions[$i % count($descriptions)];

            $frames[] = [
                'frame_number' => $i + 1,
                'image_url' => "https://picsum.photos/seed/frame{$seed}/640/360",
                'thumbnail_url' => "https://picsum.photos/seed/frame{$seed}/320/180",
                'description' => "Frame {$i}: {$description}",
                'prompt' => "{$prompt} - {$description}",
                'duration' => 2000, // 2 seconds
            ];
        }

        return [
            'success' => true,
            'frames' => $frames,
            'total_frames' => count($frames),
            'model' => 'mock-storyboard-v1',
            'metadata' => [
                'provider' => $this->name,
                'prompt_length' => strlen($prompt),
                'frame_count' => $frameCount,
                'generated_at' => now()->toISOString(),
                'placeholder' => 'Using picsum.photos for development',
            ],
        ];
    }

    public function isAvailable(): bool
    {
        return $this->enabled;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getSupportedFeatures(): array
    {
        return [
            'text' => true,
            'image' => true,
            'storyboard' => true,
            'streaming' => false,
            'custom_models' => false,
            'variations' => true,
        ];
    }

    public function setEnabled(bool $enabled): void
    {
        $this->enabled = $enabled;
    }

    /**
     * Enable/disable provider.
     */
    public function enable(): void { $this->enabled = true; }
    public function disable(): void { $this->enabled = false; }
}
